[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = { version = "5", default-features = false, features = [ "chrono" ] }
diesel = { version = "2", default-features = false }
rand = "0.8"
serde = { version = "1", features = [ "derive" ] }
thiserror = "1"
