[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2018"

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "a39c5293cbd4a4e2f677014138489c1977f07299" }
juniper = "0.15.7"
rand = "0.7.3"
serde = { version = "1.0.126", features = [ "derive" ] }
thiserror = "1.0.26"
util = { git = "https://gitlab.com/21analytics/rust-crates.git", branch = "master" }
