[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2018"

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "426b8130cf3f1be10c059d585bcfa0192ea2a561" }
juniper = { git = "https://github.com/graphql-rust/juniper", rev = "509438a5bee704737fd1165dbec8a31cdfe8bd39" }
rand = "0.7.3"
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1.0.23"
util = { path = "../util" }
