[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2021"

[dependencies]
codegen = { path = "../codegen" }
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "37ec18f46ced2d6e9197414156fdb705d7a61426" }
juniper = "0.15.7"
rand = "0.7.3"
serde = { version = "1.0.132", features = [ "derive" ] }
thiserror = "1.0.30"
util = { git = "https://gitlab.com/21analytics/rust-crates.git", rev = "af5aa195bb86845b3f0194e53ccb5bb4b3dc4070" }
