[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2021"

[dependencies]
codegen = { path = "../codegen" }
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "c06aa5ed88d2670d6e0d68124a6b426f22ab5079" }
juniper = "0.15.7"
rand = "0.7.3"
serde = { version = "1.0.135", features = [ "derive" ] }
thiserror = "1.0.30"
