[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.62"
async-graphql = { version = "4.0.13", features = [ "chrono" ] }
diesel = { version = "2.0.0", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.144", features = [ "derive" ] }
