[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.70"
async-graphql = { version = "5.0.7", default-features = false, features = [ "chrono" ] }
diesel = { version = "2.0.4", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.163", features = [ "derive" ] }
