[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2018"

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "426b8130cf3f1be10c059d585bcfa0192ea2a561" }
futures = "0.3.6"
juniper = { git = "https://github.com/graphql-rust/juniper", rev = "0dcfb850e113a545c4d66840c55fce8eb910133e" }
rand = "0.7.3"
rusqlite = "0.23.1"
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1.0.21"
util = { path = "../util" }
