[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
codegen = { path = "../codegen" }
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "cbdfee30b206fff0aba62fa482fd837c0edd2cea", default-features = false }
juniper = "0.15.9"
rand = "0.8.5"
serde = { version = "1.0.138", features = [ "derive" ] }
thiserror = "1.0.31"
