[package]
name = "lei"
version = "0.1.0"
authors = ["21Analytics <info@21analytics.ch>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
codegen = { path = "../codegen" }
diesel = { version = "2.0.0-rc.1", default-features = false }
juniper = "0.15.10"
rand = "0.8.5"
serde = { version = "1.0.144", features = [ "derive" ] }
thiserror = "1.0.32"
